version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_prefeitura
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prefeitura
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prefeitura"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: node:20
    container_name: backend_prefeitura
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "npm install && 
              npx prisma generate && 
              npx prisma migrate dev --name init&&
              npx prisma db seed &&
              npm run dev"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/prefeitura?schema=public"
      PORT: 3001
    ports:
      - "3001:3001"
      - "5555:5555"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: node:20
    container_name: frontend_prefeitura
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
    - NEXT_PUBLIC_API_URL=http://localhost:3001
    - API_URL_SERVER=http://backend_prefeitura:3001 #
    depends_on:
      - backend